version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  # Maintain dependencies for Android Gradle project
  - package-ecosystem: "gradle"
    directory: "/apk+ublock"
    schedule:
      interval: "weekly"
    groups:
      gradle-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  # Maintain dependencies for Windows .NET projects
  - package-ecosystem: "nuget"
    directory: "/vpn/Ubour"
    schedule:
      interval: "weekly"
    groups:
      nuget-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5

  - package-ecosystem: "nuget"
    directory: "/vpn/Ubour.Tests"
    schedule:
      interval: "weekly"
    groups:
      nuget-test-dependencies:
        patterns:
          - "*"
    open-pull-requests-limit: 5
