<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <AssemblyName>Ubour</AssemblyName>
    <RootNamespace>Ubour</RootNamespace>
    <PublishSingleFile>false</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <Version>1.6.1</Version>
    <AssemblyVersion>1.6.1.0</AssemblyVersion>
    <FileVersion>1.6.1.0</FileVersion>
    <InformationalVersion>1.6.1</InformationalVersion>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>

</Project>